name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up openjdk:15
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '15.0.9+5'
          
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle and analyze with Sonarqube
        run: clientSecret=${{secrets.clientSecret}} redirectURL=${{secrets.redirectURL}} SPRING_DATASOURCE_PASSWORD=${{secrets.SPRING_DATASOURCE_PASSWORD}} SPRING_DATASOURCE_URL=${{secrets.SPRING_DATASOURCE_URL}} SPRING_DATASOURCE_USERNAME=${{secrets.SPRING_DATASOURCE_URL}} GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}} SONAR_TOKEN=${{secrets.SONAR_TOKEN}} ./gradlew clean build sonarqube --info
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
      - name: Build and push (including latest tag)
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{secrets.dockerhub_username}}/${{secrets.repo_name}}:${{github.sha}},${{secrets.dockerhub_username}}/${{secrets.repo_name}}:latest
